name: Build BYOS VMSS artifact

on:
  repository_dispatch:
    types: [ byos-vmss-package, byos-package, all-package ]
  workflow_dispatch:

env:
  offerName: "eap-rhel-byos-vmss"

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rhel-jboss-templates
        uses: actions/checkout@v4

      - name: build
        id: build
        uses: ./.github/actions/build
        with:
          offerName: ${{ env.offerName }}
          token: ${{ secrets.GITHUB_TOKEN }}
          workflowType: "build"
