name: Build PAYG single artifact

on:
  repository_dispatch:
    types: [ payg-single-package, payg-package, all-package ]
  workflow_dispatch:

env:
  offerName: "eap74-rhel8-payg"

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rhel-jboss-templates
        uses: actions/checkout@v4

      - name: build
        id: build
        uses: ./.github/actions/build
        with:
          offerName: ${{ env.offerName }}
          token: ${{ secrets.GITHUB_TOKEN }}
          buildType: "build"
