name: Build EAP on ARO artifact

on:
  repository_dispatch:
    types: [ eap-aro-package, aro-package, all-package ]
  workflow_dispatch:

env:
  offerName: "eap-aro"

jobs:
  preflight:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout rhel-jboss-templates
        uses: actions/checkout@v4

      - name: build
        id: build
        uses: ./.github/actions/build
        with:
          offerName: ${{ env.offerName }}
          token: ${{ secrets.GITHUB_TOKEN }}
