# You can use `az ad sp create-for-rbac --sdk-auth` to create service principal credentials
- name: AZURE_CREDENTIALS_BYOS
  value: ""
  description: Azure Credentials used for validate-byos-* workflows.
# You can use `az ad sp create-for-rbac --sdk-auth` to create service principal credentials
- name: AZURE_CREDENTIALS_PAYG
  value: ""
  description: Azure Credentials used for validate-payg-* workflows.
# User name of your GitHub account
- name: USER_NAME
  value: ""
  description: User name of GitHub account
# User email of your GitHub account
- name: USER_EMAIL
  value: ""
  description: user Email of GitHub acount to access GitHub repository
# User name for JBoss EAP Manager
- name: RHSM_USERNAME
  value: ""
  description: RHSM userid
# User password for JBoss EAP Manager
- name: RHSM_PASSWORD
  value: ""
  description: RHSM password
#  Red Hat Subscription Manager Pool ID (Should have EAP entitlement)
- name: RHSM_POOL
  value: ""
  description: RHSM Pool ID with EAP entitlement
- name: RHSM_POOL_FOR_RHEL
  value: ""
  description: RHSM Pool ID with RHEL entitlement
# To get pull secret text, see Get a Red Hat pull secret.
# - https://learn.microsoft.com/azure/openshift/tutorial-create-cluster?WT.mc_id=Portal-fx#get-a-red-hat-pull-secret-optional
- name: PULL_SECRET
  value: ""
  description: PULL_SECRET used in the OpenShift validate-eap-aro.yaml workflow.
- name: VM_PASSWORD
  value: "Secret123456"
  description: Password for vm azureadmin user
- name: JBOSS_EAP_USER_PASSWORD
  value: "Secret123456"
  description: Password for jbossadmin user
- name: DATABASE_PASSWORD
  value: "Secret123456"
  description: Password for database user 'testuser'
- name: LOCATION
  value: "eastus"
  description: The location of the resource group.