name: Internal Action Test JavaEE Cafe
run-name:  Test JavaEE Cafe with `jdkVersion`:${{ inputs.jdkVersion }}

on:
  workflow_dispatch:
    inputs:
      jdkVersion:
        description: 'jdkVersion'
        required: true
        default: 'eap8-openjdk17'
        type: choice
        options:
          - eap8-openjdk17
          - eap8-openjdk11
          - eap74-openjdk17
          - eap74-openjdk11
          - eap74-openjdk8

env:
  azureCredentials: ${{ secrets.AZURE_CREDENTIALS_BYOS }}
  location: eastus2
  resourceGroup: test-javaee-cafe-${{ github.repository_owner }}-${{ github.run_id }}-${{ github.run_number }}
  storageAccountName: sa${{ github.run_id }}${{ github.run_number }}

jobs:
  deploy-dependent-resources:
    runs-on: ubuntu-latest
    steps:
      - name: checkout rhel-jboss-templates
        uses: actions/checkout@v4
      - uses: azure/login@v1
        id: azure-login
        with:
          creds: ${{ env.azureCredentials }}
      - name: Create Resource Group
        run: |
          az group create -n ${{ env.resourceGroup}} -l ${{ env.location }}
      - name: Build and upload javaee cafe
        id: build-and-upload-javaee-cafe
        uses: ./.github/actions/build-and-upload-javaee-cafe
        with:
          jdkVersion: ${{ inputs.jdkVersion }}
          storageAccountName: ${{ env.storageAccountName }}
          resourceGroup: ${{ env.resourceGroup }}
          location: ${{ env.location }}
          enableDB: false

  resource-clean-up:
    runs-on: ubuntu-latest
    needs: deploy-dependent-resources
    steps:
      - name: checkout rhel-jboss-templates
        uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ env.azureCredentials }}
      - name: delete resource group
        run: |
          az group delete -n ${{ env.resourceGroup }} --yes --no-wait