name: Internal Action Test generateMatrix
run-name:  Test generateMatrix with `offerName`:${{ inputs.offerName }}

on:
  workflow_dispatch:
    inputs:
      offerName:
        description: "Offer to build artifact "
        required: true
        type: choice
        default: all
        options:
          - mssqlserver
          - mssqlserver-passwordless
          - oracle
          - mysql(flexible)
          - mysql-passwordless(flexible)
          - postgresql(flexible)
          - postgresql-passwordless(flexible)
          - all

jobs:
  generateMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          if [ "${{ inputs.offerName }}" == "all" ]; then
            echo '{
              "offerName": [
                "mssqlserver",
                "mssqlserver-passwordless",
                "mysql(flexible)",
                "mysql-passwordless(flexible)",
                "postgresql(flexible)",
                "postgresql-passwordless(flexible)"
              ]
            }' | jq -c '.' | sed 's/^/matrix=/' >> "$GITHUB_OUTPUT"
          else
            echo '{
              "offerName": [
                "${{ inputs.offerName }}"
              ]
            }' | jq -c '.' | sed 's/^/matrix=/' >> "$GITHUB_OUTPUT"
          fi

  test-database:
    needs: generateMatrix
    runs-on: ubuntu-latest
    strategy:
      matrix: ${{fromJson(needs.generateMatrix.outputs.matrix)}}
    steps:
        - name: Checkout rhel-jboss-templates
          uses: actions/checkout@v4

