name: Internal Action Test Database provision
run-name:  Test database provision with `db`:${{ inputs.databaseType }}

on:
  workflow_dispatch:
    inputs:
      databaseType:
        description: 'Database connection'
        required: true
        default: 'mssqlserver'
        type: choice
        options:
          - mssqlserver
          - mssqlserver-passwordless
          - oracle
          - mysql(flexible)
          - mysql-passwordless(flexible)
          - postgresql(flexible)
          - postgresql-passwordless(flexible)
          - none

env:
  azureCredentials: ${{ secrets.AZURE_CREDENTIALS_BYOS }}
  location: eastus2
  resourceGroup: test-db-provision-${{ github.repository_owner }}-${{ github.run_id }}-${{ github.run_number }}
  password: ${{ secrets.VM_PASSWORD }}
  dbInstanceName: db${{ github.run_id }}${{ github.run_number }}
  dbPassword: ${{ secrets.DATABASE_PASSWORD }}
  uamiName: uami${{ github.run_id }}${{ github.run_number }}
  scriptLocation: https://raw.githubusercontent.com/${{ secrets.USER_NAME }}/rhel-jboss-templates/$GITHUB_REF_NAME/utilities/

jobs:
  deploy-dependent-resources:
    runs-on: ubuntu-latest
    outputs:
      serverHost: ${{ steps.database-provision.outputs.sqlserverHost }}
      uamiId: ${{ steps.database-provision.outputs.uamiId }}
    steps:
      - name: checkout rhel-jboss-templates
        uses: actions/checkout@v4
      - uses: azure/login@v1
        id: azure-login
        with:
          creds: ${{ env.azureCredentials }}
      - name: Create Resource Group
        run: |
          az group create -n ${{ env.resourceGroup}} -l ${{ env.location }}
      - name: Provision database
        id: database-provision
        uses: ./.github/actions/database-provision
        with:
          databaseType: ${{ inputs.databaseType }}
          resourceGroup: ${{ env.resourceGroup }}
          uamiName: ${{ env.uamiName }}
          location: ${{ env.location }}
          dbInstanceName: ${{ env.dbInstanceName }}
          dbPassword: ${{ env.dbPassword }}
          scriptLocation: ${{env.scriptLocation}}
      - name: Get database parameters
        id: database-parameters
        uses: ./.github/actions/database-parameters
        with:
          databaseType: ${{ inputs.databaseType }}
          uamiId: ${{ steps.database-provision.outputs.uamiId }}
          serverHost: ${{ steps.database-provision.outputs.serverHost }}
          dbInstanceName: ${{ env.dbInstanceName }}
      - name: Prepare parameter file
        run: |
          databaseType=${{ steps.database-parameters.outputs.databaseType }}
          enableDB=${{ steps.database-parameters.outputs.enableDB }}
          enablePasswordless=${{ steps.database-parameters.outputs.enablePasswordless }}
          dbUser=${{ steps.database-parameters.outputs.dbUser }}
          dbPassword=${{ env.dbPassword }}
          dsConnectionURL=${{ steps.database-parameters.outputs.dsConnectionURL }}
          dbIdentity='${{ steps.database-parameters.outputs.dbIdentity }}'
          
          # use heredoc to echo the values with json format to file parameters-output.json
          cat <<EOF > parameters-output.json
          {
              "databaseType": "$databaseType",
              "enableDB": $enableDB,
              "enablePasswordless": $enablePasswordless,
              "dbUser": "$dbUser",
              "dbPassword": "$dbPassword",
              "dsConnectionURL": "$dsConnectionURL",
              "dbIdentity": $dbIdentity
          }

      - name: Archive parameters-output.json
        uses: actions/upload-artifact@v4.6.2
        if: success()
        with:
          name: parameters-output
          path: ./parameters-output.json
      - name: Setup tmate session
        if: ${{ failure() }}
        uses: mxschmitt/action-tmate@v3
      - name: Set outputs
        run: |
          echo "serverHost=${{ steps.database-provision.outputs.serverHost }}" 
          echo "uamiId=${{ steps.database-provision.outputs.uamiId }}"
          echo dbIdentity='${{ steps.database-parameters.outputs.dbIdentity }}'

  resource-clean-up:
    runs-on: ubuntu-latest
    needs: deploy-dependent-resources
    if: ${{ always() }}
    steps:
      - name: checkout rhel-jboss-templates
        uses: actions/checkout@v4
      - uses: azure/login@v1
        with:
          creds: ${{ env.azureCredentials }}
      - name: delete resource group
        run: |
          az group delete -n ${{ env.resourceGroup }} --yes --no-wait