name: Internal Action Test generateMatrix02
run-name:  Test generateMatrix02 with `offerName`:${{ inputs.offerName }}

on:
  workflow_dispatch:
    inputs:
      offerName:
        description: "Offer to build artifact "
        required: true
        type: choice
        default: all
        options:
          - eap-rhel-byos
          - eap-rhel-byos-multivm
          - eap-rhel-payg
          - eap-rhel-payg-multivm
          - eap-aro
          - all

env:
  azureCredentials: ${{ secrets.AZURE_CREDENTIALS_BYOS }}
  location: eastus2
  resourceGroupPrefix: test-db-provision-${{ github.repository_owner }}-${{ github.run_id }}-${{ github.run_number }}
  password: ${{ secrets.VM_PASSWORD }}
  dbInstanceName: db${{ github.run_id }}${{ github.run_number }}
  dbPassword: ${{ secrets.DATABASE_PASSWORD }}
  uamiName: uami${{ github.run_id }}${{ github.run_number }}
  scriptLocation: https://raw.githubusercontent.com/${{ secrets.USER_NAME }}/rhel-jboss-templates/$GITHUB_REF_NAME/utilities/

jobs:
  generateMatrix:
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - name: Generate matrix
        id: set-matrix
        run: |
          if [ "${{ inputs.offerName }}" == "all" ]; then
            echo '{
              "offerName": [
                "eap-rhel-byos",
                "eap-rhel-byos-multivm",
                "eap-rhel-payg",
                "eap-rhel-payg-multivm",
                "eap-aro"
              ]
            }' | jq -c '.' | sed 's/^/matrix=/' >> "$GITHUB_OUTPUT"
          else
            echo '{
              "offerName": [
                "${{ inputs.offerName }}"
              ]
            }' | jq -c '.' | sed 's/^/matrix=/' >> "$GITHUB_OUTPUT"
          fi
          

  output-matrix:
    needs: generateMatrix
    runs-on: ubuntu-latest
    steps:
      - name: echo the matrix
        run: |
          echo ${{ needs.generateMatrix.outputs.matrix }} > matrix.json

      - name: echo the jsonmatrix
        run: |
          echo ${{ fromJson(needs.generateMatrix.outputs.matrix) }} > jsonmatrix.json

      - name: Setup tmate session
        uses: mxschmitt/action-tmate@v3
          
