name: IT Validation Multi-VM PAYG
run-name: Running validation workflows with plan:${{ inputs.it_plan }}

on:
  schedule:
    - cron: '0 12 1 * *'  # Runs on the 1st of every month at 12:00 PM (noon) UTC
  workflow_dispatch:
    inputs:
      it_plan:
        description: 'Path to the validation plan file'
        required: true
        type: choice
        options:
          - multivm-payg-plan
        default: multivm-payg-plan

jobs:
  execute-validation:
    runs-on: ubuntu-latest
    outputs:
      results: ${{ steps.it-validation.outputs.results }}
      report_url: ${{ steps.it-validation.outputs.report_url }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
      
      - name: Set validation plan file
        id: set-plan-file
        run: |
          case "${{ inputs.it_plan || 'multivm-payg-plan' }}" in
            multivm-payg-plan)
              IT_FILE=".github/it/validation-plan-multivm-payg.json"
              ;;
            *)
              echo "Unknown plan option: ${{ inputs.it_plan }}"
              exit 1
              ;;
          esac
          echo "it_file=$IT_FILE" >> $GITHUB_OUTPUT
      
      - name: Execute IT Validation
        id: it-validation
        uses: ./.github/actions/it
        with:
          it_file: ${{ steps.set-plan-file.outputs.it_file }}
          github_token: ${{ secrets.GITHUB_TOKEN }}
