name: Test Workflow with Callable Inputs

on:
  workflow_dispatch: # This workflow no longer needs separate workflow_dispatch inputs, as Common Workflow Trigger handles them

jobs:
  call_common_trigger:
    uses: ./.github/workflows/callable-workflow-inputs.yml # Replace with the path to your reusable workflow
    # When your main workflow is triggered via workflow_dispatch,
    # GitHub automatically passes the workflow_dispatch inputs to the `uses` called workflow.
    # You don't need to explicitly use `with:` here to pass the inputs,
    # unless you want to override some default values.
    # For example:
    # with:
    #   databaseType: 'oracle'

  my_actual_job:
    needs: call_common_trigger # Ensure this job runs after 'call_common_trigger' completes
    runs-on: ubuntu-latest
    steps:
      - name: Use Inputs from Reusable Workflow
        run: |
          echo "Database Type used in actual workflow: ${{ needs.call_common_trigger.outputs.databaseType }}"
          echo "JDK Version used in actual workflow: ${{ needs.call_common_trigger.outputs.jdkVersion }}"
          echo "Wait Time before Delete used in actual workflow: ${{ needs.call_common_trigger.outputs.timeWaitBeforeDelete }}"
      - name: Do something with these inputs
        run: |
          # Your actual business logic goes here, utilizing the passed inputs
          echo "Running build with database type: ${{ needs.call_common_trigger.outputs.databaseType }}"