name: Test url health

on:
  workflow_dispatch:
    inputs:
      endpoint:
        description: "The application endpoint to check."
        required: true
        default: "https://www.google.com"

jobs:
    deploy-dependent-resources:
        runs-on: ubuntu-latest
        steps:
            - name: checkout rhel-jboss-templates
              uses: actions/checkout@v4
            - name:  endpoint health check
              uses: ./.github/actions/url-health-check
              with:
                appEndpoint: ${{ github.event.inputs.endpoint }}
                maxRetries: 10
                retryInterval: 5
