name: Test url health

on:
  workflow_dispatch:
    inputs:

jobs:
    deploy-dependent-resources:
        runs-on: ubuntu-latest
        steps:
            - name: checkout rhel-jboss-templates
              uses: actions/checkout@v4
            - name: Verify console is accessible
              uses: ./.github/actions/url-health-check
              with:
                appEndpoint: "https://www.sjksjdfsjfl-gzh-for-test.com"
                maxRetries: 10
                retryInterval: 15
