name: Validate byos offer
run-name: Validate byos offer with `jdk`:${{ inputs.jdkVersion }} and `db`:${{ inputs.databaseType }}

on:
  workflow_dispatch:
    inputs:
      databaseType:
        description: 'Database connection'
        required: true
        default: 'mssqlserver'
        type: choice
        options:
        - mssqlserver
        - oracle
        - mysql(flexible)
        - mysql-passwordless(flexible)
        - postgresql(flexible)
        - postgresql-passwordless(flexible)
        - none
      jdkVersion:
        description: 'jdkVersion'
        required: true
        default: 'eap8-openjdk17'
        type: choice
        options:
          - eap8-openjdk17
          - eap8-openjdk11
          - eap74-openjdk17
          - eap74-openjdk11
          - eap74-openjdk8
      timeWaitBeforeDelete:
        description: 'Choose the wait time before deleting resources: 30m (30 minutes), 2h (2 hours), 5h (5 hours), 0 (immediately)'
        required: true
        type: choice
        default: 0
        options:
          - 30m
          - 2h
          - 5h
          - 0

env:
    azCliVersion: 2.72.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS_BYOS }}
    location: eastus2
    singleResourceGroup: single-${{ github.repository_owner }}-${{ github.run_id }}-${{ github.run_number }}
    vmName: ${{ github.run_id }}${{ github.run_number }}vm
    adminUsername: azureadmin
    password: ${{ secrets.VM_PASSWORD }}
    dbInstanceName: db${{ github.run_id }}${{ github.run_number }}
    dbPassword: ${{ secrets.DATABASE_PASSWORD }}
    uamiName: uami${{ github.run_id }}${{ github.run_number }}
    singleStorageAccountName: singlesa
    jbossEAPUserName: jbossadmin
    jbossEAPPassword: ${{ secrets.JBOSS_EAP_USER_PASSWORD }}
    rhsmUserName: ${{ secrets.RHSM_USERNAME }}
    rhsmPassword: ${{ secrets.RHSM_PASSWORD }}
    rhsmPoolEAP: ${{ secrets.RHSM_POOL }}
    rhsmPoolRHEL: ${{ secrets.RHSM_POOL_FOR_RHEL }}
    gitUserName: ${{ secrets.USER_NAME }}
    gitEmail: ${{ secrets.USER_EMAIL }}
    testPubIpName: testPubIp
    nsgName: jbosseap-nsg
    scriptLocation: https://raw.githubusercontent.com/${{ secrets.USER_NAME }}/rhel-jboss-templates/$GITHUB_REF_NAME/utilities/
    offerName: "eap-rhel-byos"
    gracefulShutdownTimeout: "-1"

jobs:
    preflight:
        outputs:
          artifactName: ${{steps.build.outputs.artifactName}}
        runs-on: ubuntu-latest
        steps:
            - name: Checkout rhel-jboss-templates
              uses: actions/checkout@v4
            - name: build
              id: build
              uses: ./.github/actions/build
              with:
                offerName: ${{ env.offerName }}
                token: ${{ secrets.GITHUB_TOKEN }}
                workflowType: "validate"
    deploy-single:
        needs: preflight
        runs-on: ubuntu-latest
        steps:
            - name: Checkout rhel-jboss-templates
              uses: actions/checkout@v4
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Accept Image Terms
              id: accept-terms
              run: |
                  echo "accept terms for VM image"
                  az vm image terms accept --urn redhat:rh-jboss-eap:rh-jboss-eap74-rhel8:latest
                  az vm image terms accept --urn redhat:rhel-byos:rhel-lvm94-gen2:latest
            - name: Create Resource Group
              run: |
                az group create -n ${{ env.singleResourceGroup}} -l ${{ env.location }}
            - name: Provision dabase
              id: dabase-provision
              uses: ./.github/actions/database-provision
              with:
                databaseType: ${{ inputs.databaseType }}
                resourceGroup: ${{ env.singleResourceGroup }}
                uamiName: ${{ env.uamiName }}
                location: ${{ env.location }}
                dbInstanceName: ${{ env.dbInstanceName }}
                dbPassword: ${{ env.dbPassword }}

            - name: Prepare parameter file
              run: |
                enableDB=false
                databaseType=postgresql
                dsConnectionURL=jdbc:postgresql://contoso.postgres.database:5432/testdb
                dbUser=contosoDbUser
                dbPassword=contosoDbPwd
                enablePasswordless=false
                dbIdentity={}
                serverHost=${{ steps.dabase-provision.outputs.serverHost }}
                uamiId=${{ steps.dabase-provision.outputs.uamiId }}
                if ${{ inputs.databaseType == 'mssqlserver' || github.event.client_payload.databaseType == 'mssqlserver' }}; then
                  enableDB=true
                  databaseType=mssqlserver
                  dsConnectionURL="jdbc:sqlserver://$serverHost:1433;database=testdb"
                  dbUser=testuser@${{ env.dbInstanceName }}
                  dbPassword=${{ env.dbPassword }}
                elif ${{ inputs.databaseType == 'oracle' || github.event.client_payload.databaseType == 'oracle' }}; then
                  enableDB=true
                  databaseType=oracle
                  publicIp=$(az vm show -g ${{ env.singleResourceGroup }} -n ${{ env.dbInstanceName }} -d --query publicIps -o tsv)
                  dsConnectionURL=jdbc:oracle:thin:@${publicIp}:1521/oratest1
                  dbUser=testuser
                  dbPassword=${{ env.dbPassword }}
                elif ${{ inputs.databaseType == 'mysql(flexible)' || github.event.client_payload.databaseType == 'mysql(flexible)' }}; then
                  enableDB=true
                  databaseType=mysql
                  dsConnectionURL=jdbc:mysql://$serverHost:3306/testdb?sslMode=REQUIRED
                  dbUser=testuser
                  dbPassword=${{ env.dbPassword }}
                elif ${{ inputs.databaseType == 'mysql-passwordless(flexible)' || github.event.client_payload.databaseType == 'mysql-passwordless(flexible)' }}; then
                  enableDB=true
                  enablePasswordless=true
                  dbUser=$(basename "$uamiId")
                  dbIdentity=$(jq -n \
                                --arg uamiId "$uamiId" \
                                '{
                                      "type": "UserAssigned",
                                      "userAssignedIdentities": {
                                          ($uamiId): {}
                                      }
                                  }'| jq -c '.')
                  databaseType=mysql
                  dsConnectionURL=jdbc:mysql://$serverHost:3306/testdb
                elif ${{ inputs.databaseType == 'postgresql(flexible)' || github.event.client_payload.databaseType == 'postgresql(flexible)' }}; then
                  enableDB=true
                  databaseType=postgresql
                  dsConnectionURL="jdbc:postgresql://$serverHost:5432/testdb"
                  dbUser=testuser
                  dbPassword=${{ env.dbPassword }}
                elif ${{ inputs.databaseType == 'postgresql-passwordless(flexible)' || github.event.client_payload.databaseType == 'postgresql-passwordless(flexible)' }}; then
                  echo "set parameter for passwordless postgresql"
                  enableDB=true
                  enablePasswordless=true
                  dbUser=$(basename "$uamiId")
                  dbIdentity=$(jq -n \
                                --arg uamiId "$uamiId" \
                                '{
                                      "type": "UserAssigned",
                                      "userAssignedIdentities": {
                                          ($uamiId): {}
                                      }
                                  }'| jq -c '.')  
                  databaseType=postgresql
                  dsConnectionURL="jdbc:postgresql://$serverHost:5432/testdb"
                fi

                echo "generate parameter file for single"
                bash rhel-jboss-templates/eap-rhel-byos/src/test/scripts/gen-parameters.sh \
                <<< "rhel-jboss-templates/eap-rhel-byos/src/test/parameters-test-single.json  \
                ${gitUserName} \
                ${{ github.sha }} \
                ${location} \
                ${vmName} \
                ${adminUsername} \
                ${password} \
                ${singleResourceGroup} \
                ${singleStorageAccountName} \
                ${singleResourceGroup} \
                ${jbossEAPUserName} \
                ${jbossEAPPassword} \
                ${rhsmUserName} \
                ${rhsmPassword} \
                ${rhsmPoolEAP} \
                ${rhsmPoolRHEL} \
                ${enableDB} \
                ${databaseType} \
                java:jboss/datasources/JavaEECafeDB \
                ${dsConnectionURL} \
                ${dbUser} \
                ${dbPassword} \
                ${{ inputs.jdkVersion }} \
                ${{ env.gracefulShutdownTimeout }} \
                ${enablePasswordless} \
                ${dbIdentity}"

            - name: Archive parameters-test-single.json
              uses: actions/upload-artifact@v4.6.2
              if: success()
              with:
                name: parameters-test-single
                path: rhel-jboss-templates/eap-rhel-byos/src/test/parameters-test-single.json
            - name: Deploy JBoss EAP single
              id: deploy-single
              uses: azure/cli@v2
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group create \
                    --verbose \
                    --resource-group ${{ env.singleResourceGroup }} \
                    --name single \
                    --parameters @rhel-jboss-templates/eap-rhel-byos/src/test/parameters-test-single.json \
                    --template-file rhel-jboss-templates/eap-rhel-byos/mainTemplate.json
            - name: Get public IP
              id: get_public_ip
              uses: azure/cli@v2
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    publicip=$(az network public-ip list --resource-group $singleResourceGroup --query "[?starts_with(name, 'jbosseapVm-ip')].ipAddress" -o tsv)
                    echo "##[set-output name=publicip;]${publicip}"
            - name: Verify console is accessible
              run: |
                publicip=${{steps.get_public_ip.outputs.publicip}}
                echo "publicip: " $publicip
                CURL_RETRY_PARMS="--connect-timeout 60 --max-time 180 --retry 10 --retry-delay 30 --retry-max-time 180 --retry-connrefused"
                echo "Verifying console is accessible"
                curl --verbose http://${publicip}:9990/console/index.html
                response=$(curl ${CURL_RETRY_PARMS}  --write-out '%{http_code}' --silent --output /dev/null http://${publicip}:9990/console/index.html)
                echo "$response"
                if [ "$response" -ne 200 ]; then
                  echo "console is not accessible"
                  exit 1
                else
                  echo "console is accessible"
                fi
                exit 0

    resources-cleanup:
      name: resources-cleanup after ${{ github.event.inputs.timeWaitBeforeDelete }}
      needs:
        - preflight
        - deploy-single
      if: always()
      runs-on: ubuntu-latest
      steps:
        - uses: azure/login@v1
          id: azure-login
          with:
            creds: ${{ env.azureCredentials }}
        - name: Checkout rhel-jboss-templates
          uses: actions/checkout@v4
          with:
            path: rhel-jboss-templates
        - name: Pause ${{ github.event.inputs.timeWaitBeforeDelete }} before deleting resources
          run: |
            echo "Sleeping for ${{ github.event.inputs.timeWaitBeforeDelete }}"
            sleep ${{ github.event.inputs.timeWaitBeforeDelete }}
        - name: Delete Resource Group
          if: ${{ github.event_name == 'workflow_dispatch' }}
          id: delete-resource-group
          run: |
            echo "delete... " $singleResourceGroup
            az group delete --yes --no-wait --verbose --name $singleResourceGroup
