name: Validate byos-vmss offer

on:
  workflow_dispatch:
    inputs:
      databaseType:
        description: 'Database connection'
        required: true
        default: 'mssqlserver'
        type: choice
        options:
        - mssqlserver
        - postgresql
        - none
      isForDemo:
        description: 'If set to true, resources will not be deleted'
        required: true
        default: 'false'

env:
    azCliVersion: 2.30.0
    azureCredentials: ${{ secrets.AZURE_CREDENTIALS }}
    location: eastus
    vmssResourceGroup: vmss-${{ github.run_id }}-${{ github.run_number }}
    vmName: ${{ github.run_id }}${{ github.run_number }}vm
    vmssName: jbossvmss
    asName: ${{ github.run_id }}${{ github.run_number }}as
    adminUsername: azureadmin
    password: ${{ secrets.VM_PASSWORD }}
    numberOfInstances: 3
    vmssBootStorageAccountName: ${{ github.run_id }}${{ github.run_number }}vmsssa
    jbossEAPUserName: jbossadmin
    jbossEAPPassword: ${{ secrets.JBOSS_EAP_USER_PASSWORD }}
    rhsmUserName: ${{ secrets.RHSM_USERNAME }}
    rhsmPassword: ${{ secrets.RHSM_PASSWORD }}
    rhsmPoolEAP: ${{ secrets.RHSM_POOL }}
    rhsmPoolRHEL: ${{ secrets.RHSM_POOL_FOR_RHEL }}
    userAssignedManagedIdentity: ${{ secrets.USER_ASSIGNED_MANAGED_IDENTITY_ID }}
    dbInstanceName: db${{ github.run_id }}${{ github.run_number }}
    dbPassword: ${{ secrets.DATABASE_PASSWORD }}
    gitUserName: ${{ secrets.USER_NAME }}
    vmssTestBranchName: vmss-cicd-${{ github.run_id }}-${{ github.run_number }}
    gitEmail: ${{ secrets.USER_EMAIL }}
    gitToken: ${{ secrets.GIT_TOKEN }}
    enableLoadBalancer: enable
    disableLoadBalancer: disable

jobs:
    preflight:
        outputs:
          isForDemo: ${{ steps.setup-env-variables-based-on-dispatch-event.outputs.isForDemo }}
        runs-on: ubuntu-latest
        steps:
            - name: Get versions of external dependencies
              run: |
                curl -Lo external-deps-versions.properties https://raw.githubusercontent.com/Azure/azure-javaee-iaas/main/external-deps-versions.properties
                source external-deps-versions.properties
                echo "azCliVersion=${AZ_CLI_VERSION}" >> $GITHUB_ENV
                echo "bicepVersion=${BICEP_VERSION}" >> $GITHUB_ENV
                echo "refArmttk=${ARM_TTK_REFERENCE}" >> $GITHUB_ENV
                echo "refJavaee=${AZURE_JAVAEE_IAAS_REFERENCE}" >> $GITHUB_ENV
            - name: Set up JDK 11
              uses: actions/setup-java@v3
              with:
                distribution: 'temurin'
                java-version: '11'
            - name: Set up bicep
              run: |
                curl -Lo bicep https://github.com/Azure/bicep/releases/download/${{ env.bicepVersion }}/bicep-linux-x64
                chmod +x ./bicep
                sudo mv ./bicep /usr/local/bin/bicep
                bicep --version
            - name: Checkout azure-javaee-iaas
              uses: actions/checkout@v3
              with:
                repository: Azure/azure-javaee-iaas
                path: azure-javaee-iaas
                ref: ${{ env.refJavaee }}
            - name: Checkout arm-ttk
              uses: actions/checkout@v3
              with:
                repository: Azure/arm-ttk
                path: arm-ttk
                ref: ${{ env.refArmttk }}
            - name: Build azure-javaee-iaas
              run: mvn -DskipTests clean install --file azure-javaee-iaas/pom.xml
            - name: Checkout rhel-jboss-templates
              uses: actions/checkout@v3
              with:
                repository: ${{env.gitUserName}}/rhel-jboss-templates
                path: rhel-jboss-templates
            - name: Build and test rhel-jboss-templates
              run: |
                mvn -Pbicep -Passembly clean install -Ptemplate-validation-tests --file rhel-jboss-templates/eap74-rhel8-byos-vmss/pom.xml
            - name: Generate artifact file name and path
              id: artifact_file
              run: |
                vmssVersion=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.version}' --non-recursive exec:exec --file rhel-jboss-templates/eap74-rhel8-byos-vmss/pom.xml)
                vmssArtifactName=$(mvn -q -Dexec.executable=echo -Dexec.args='${project.artifactId}' --non-recursive exec:exec --file rhel-jboss-templates/eap74-rhel8-byos-vmss/pom.xml)
                vmssArtifactName=${vmssArtifactName}-${vmssVersion}-arm-assembly
                unzip rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}.zip -d rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}
                # Move eap-session-replication.war from /bin to /scripts, a workaround for publishing private plan in Partner center, see issue: https://github.com/Azure/rhel-jboss-templates/issues/108
                # This change is coupled with eap74-rhel8-byos-vmss/src/main/bicep/mainTemplate.bicep#165
                cp -R rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}/bin/. rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}/scripts/
                # Delete /bin 
                rm -r rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}/bin
                echo "##[set-output name=vmssArtifactName;]${vmssArtifactName}"
                echo "##[set-output name=vmssArtifactPath;]rhel-jboss-templates/eap74-rhel8-byos-vmss/target/${vmssArtifactName}"
            - name: Archive rhel-jboss-templates eap74-rhel8-byos-vmss offer templates
              uses: actions/upload-artifact@v3
              if: success()
              with:
                name: ${{steps.artifact_file.outputs.vmssArtifactName}}
                path: ${{steps.artifact_file.outputs.vmssArtifactPath}}
            - name: Setup environment variables
              id: setup-env-variables-based-on-dispatch-event
              run: |
                isForDemo=${{ github.event.inputs.isForDemo }}
                echo "##[set-output name=isForDemo;]${isForDemo}"
                echo "isForDemo=${isForDemo}" >> $GITHUB_ENV
    deploy-vmss:
        needs: preflight
        runs-on: ubuntu-latest
        steps:
            - name: Checkout rhel-jboss-templates
              uses: actions/checkout@v3
              with:
                repository: ${{env.gitUserName}}/rhel-jboss-templates
                path: rhel-jboss-templates
            - name: Output artifact name and version for Download action
              id: artifact_file
              run: |
                vmssVersion=$(awk '/<version>[^<]+<\/version>/{gsub(/<version>|<\/version>/,"",$1);print $1;exit;}' rhel-jboss-templates/eap74-rhel8-byos-vmss/pom.xml)
                vmssArtifactName=eap74-rhel8-byos-vmss-${vmssVersion}-arm-assembly

                echo "##[set-output name=vmssArtifactName;]${vmssArtifactName}"
            - name: Download artifact for test branch
              uses: actions/download-artifact@v1
              with:
                name: ${{steps.artifact_file.outputs.vmssArtifactName}}
                path: rhel-jboss-templates-dev
            - name: Create a new branch with built artifact
              run: |
                current=`pwd`
                echo "current=${current}" >> $GITHUB_ENV
                cd rhel-jboss-templates
                git config --global core.longpaths true
                git config --global user.email $gitEmail
                git config --global user.name $gitUserName
                echo "create branch $vmssTestBranchName"
                git checkout -b $vmssTestBranchName
                rm -r -f $current/rhel-jboss-templates/eap74-rhel8-byos-vmss/src/main/*
                cp -r -f $current/rhel-jboss-templates-dev/* $current/rhel-jboss-templates/eap74-rhel8-byos-vmss/
                git add .
                git status
                git commit -m "test branch for pipeline"
                git push https://$gitToken@github.com/${GITHUB_REPOSITORY}.git -f
            - uses: azure/login@v1
              id: azure-login
              with:
                creds: ${{ env.azureCredentials }}
            - name: Accept Image Terms
              id: accept-terms
              run: |
                  echo "accept terms for VM image"
                  az vm image terms accept --urn redhat:rhel-byos:rhel-lvm84:latest
            - name: Deploy an instance of Azure SQL Database
              if: ${{ inputs.databaseType == 'mssqlserver' || github.event.client_payload.databaseType == 'mssqlserver' }}
              run: |
                az group create -n ${{ env.vmssResourceGroup}} -l ${{ env.location }}
                az sql server create \
                  --resource-group ${{ env.vmssResourceGroup }} --name ${{ env.dbInstanceName }} \
                  --admin-user testuser --admin-password ${{ env.dbPassword }} \
                  --location ${{ env.location }}
                host=$(az sql server show \
                  --resource-group ${{ env.vmssResourceGroup }} --name ${{ env.dbInstanceName }} \
                  --query "fullyQualifiedDomainName" -o tsv)
                echo "sqlserverHost=${host}" >> $GITHUB_ENV
                # Allow Azure services to access
                az sql server firewall-rule create \
                  --resource-group ${{ env.vmssResourceGroup }} --server ${{ env.dbInstanceName }} \
                  --name "AllowAllAzureIps" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
                az sql db create --resource-group ${{ env.vmssResourceGroup }} --server ${{ env.dbInstanceName }} --name testdb
            - name: Deploy an instance of Azure Database for PostgreSQL
              if: ${{ inputs.databaseType == 'postgresql' || github.event.client_payload.databaseType == 'postgresql' }}
              run: |
                az group create -n ${{ env.vmssResourceGroup}} -l ${{ env.location }}
                az postgres server create \
                  --resource-group ${{ env.vmssResourceGroup}} --name ${{ env.dbInstanceName }} \
                  --admin-user testuser --admin-password ${{ env.dbPassword }} \
                  --location ${{ env.location }}
                host=$(az postgres server show \
                  --resource-group ${{ env.vmssResourceGroup}} --name ${{ env.dbInstanceName }} \
                  --query "fullyQualifiedDomainName" -o tsv)
                echo "postgresqlHost=${host}" >> $GITHUB_ENV
                # Allow Azure services to access
                az postgres server firewall-rule create \
                  --resource-group ${{ env.vmssResourceGroup}} --server ${{ env.dbInstanceName }} \
                  --name "AllowAllAzureIps" --start-ip-address 0.0.0.0 --end-ip-address 0.0.0.0
                az postgres db create --resource-group ${{ env.vmssResourceGroup}} --server ${{ env.dbInstanceName }} --name testdb
            - name: Prepare parameter file
              run: |
                enableDB=false
                databaseType=postgresql
                dsConnectionURL=jdbc:postgresql://contoso.postgres.database:5432/testdb
                dbUser=contosoDbUser
                dbPassword=contosoDbPwd
                if ${{ inputs.databaseType == 'mssqlserver' || github.event.client_payload.databaseType == 'mssqlserver' }}; then
                  enableDB=true
                  databaseType=mssqlserver
                  dsConnectionURL="jdbc:sqlserver://${{ env.sqlserverHost }}:1433;database=testdb"
                  dbUser=testuser@${{ env.dbInstanceName }}
                  dbPassword=${{ env.dbPassword }}
                elif ${{ inputs.databaseType == 'postgresql' || github.event.client_payload.databaseType == 'postgresql' }}; then
                  enableDB=true
                  databaseType=postgresql
                  dsConnectionURL="jdbc:postgresql://${{ env.postgresqlHost }}:5432/testdb"
                  dbUser=testuser@${{ env.dbInstanceName }}
                  dbPassword=${{ env.dbPassword }}
                fi

                echo "generate parameter file for vmss"
                bash rhel-jboss-templates/eap74-rhel8-byos-vmss/src/test/scripts/gen-parameters.sh \
                <<< "rhel-jboss-templates/eap74-rhel8-byos-vmss/src/test/parameters-test-vmss.json  \
                ${gitUserName} \
                ${vmssTestBranchName} \
                ${location} \
                ${vmssName} \
                ${adminUsername} \
                ${password} \
                ${vmssResourceGroup} \
                ${vmssBootStorageAccountName} \
                ${vmssResourceGroup} \
                ${numberOfInstances} \
                ${jbossEAPUserName} \
                ${jbossEAPPassword} \
                ${rhsmUserName} \
                ${rhsmPassword} \
                ${rhsmPoolEAP} \
                ${rhsmPoolRHEL} \
                ${enableDB} \
                ${databaseType} \
                jdbc/JavaEECafeDB \
                ${dsConnectionURL} \
                ${dbUser} \
                ${dbPassword}"

            - name: Archive parameters-test-vmss.json
              uses: actions/upload-artifact@v1
              if: success()
              with:
                name: parameters-test-vmss
                path: rhel-jboss-templates/eap74-rhel8-byos-vmss/src/test/parameters-test-vmss.json
            - name: Create Resource Group if needed
              if: ${{ inputs.databaseType == 'none' || github.event.client_payload.databaseType == 'none' }}
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    echo "create resource group" ${{ env.vmssResourceGroup }}
                    az group create --verbose --name ${{ env.vmssResourceGroup }} --location ${{ env.location }}
            - name: Validate Deploy JBoss EAP VMSS
              id: validate-deploy-vmss
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group validate \
                    --verbose \
                    --resource-group ${{ env.vmssResourceGroup }} \
                    --name vmss \
                    --parameters @rhel-jboss-templates/eap74-rhel8-byos-vmss/src/test/parameters-test-vmss.json \
                    --template-file rhel-jboss-templates/eap74-rhel8-byos-vmss/mainTemplate.json
            - name: Deploy JBoss EAP VMSS
              id: deploy-vmss
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    az deployment group create \
                    --verbose \
                    --resource-group ${{ env.vmssResourceGroup }} \
                    --name vmss \
                    --parameters @rhel-jboss-templates/eap74-rhel8-byos-vmss/src/test/parameters-test-vmss.json \
                    --template-file rhel-jboss-templates/eap74-rhel8-byos-vmss/mainTemplate.json
            - name: Query public ip of Application Gateway
              id: query_app_gateway_public_ip
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                    # query public ip address of Application Gateway
                    publicip=$(az network public-ip show --name gwip \
                                --resource-group ${{ env.vmssResourceGroup }} --query dnsSettings.fqdn -o tsv)
                    echo "##[set-output name=publicip;]${publicip}"
            - name: Verify eap-session-replication application
              run: |
                publicip=${{steps.query_app_gateway_public_ip.outputs.publicip}}
                echo "publicip: " $publicip
                CURL_RETRY_PARMS="--connect-timeout 60 --max-time 180 --retry 10 --retry-delay 30 --retry-max-time 180 --retry-connrefused"

                echo "Verifying eap-session-replication is deployed as expected"
                curl --verbose http://${publicip}/eap-session-replication/
                response=$(curl ${CURL_RETRY_PARMS}  --write-out '%{http_code}' --silent --output /dev/null http://${publicip}/eap-session-replication/)
                echo "$response"
                if [ "$response" -ne 200 ]; then
                  echo "eap-session-replication is not accessible"
                  exit 1
                else
                  echo "eap-session-replication is accessible"
                fi
                exit 0
            - name: Unregister before deleting resources
              if: ${{ needs.preflight.outputs.isForDemo == 'false' }}
              uses: azure/CLI@v1
              with:
                azcliversion: ${{ env.azCliVersion }}
                inlineScript: |
                  for ((i = 0; i < numberOfInstances; i++)); do
                    echo "Unregister VMSS instance ${i}"
                    az vmss run-command invoke -g ${vmssResourceGroup} -n jbosseap-server${vmssName} --command-id RunShellScript --instance-id ${i} --scripts "sudo subscription-manager unregister"
                  done
            - name: Delete Resource Group
              id: delete-resource-group
              if: ${{ needs.preflight.outputs.isForDemo == 'false' }}
              run: |
                  echo "delete... " $vmssResourceGroup
                  az group delete --yes --no-wait --verbose --name $vmssResourceGroup
            - name: Checkout rhel-jboss-templates
              uses: actions/checkout@v3
              with:
                repository: ${{env.gitUserName}}/rhel-jboss-templates
                path: rhel-jboss-templates
            - name: Delete testing branch
              run: |
                cd rhel-jboss-templates
                git push https://$gitToken@github.com/${GITHUB_REPOSITORY}.git -f --delete $vmssTestBranchName              
